USE `trading-alpha`;

CREATE TABLE IF NOT EXISTS t_chain_order (
  f_id BIGINT NOT NULL AUTO_INCREMENT,
  f_order_id VARCHAR(64) NOT NULL,
  f_user_id BIGINT NOT NULL,
  f_wallet_address VARCHAR(64) NOT NULL,
  f_chain VARCHAR(32) NOT NULL DEFAULT 'bsc-testnet',
  f_chain_id VARCHAR(16) NOT NULL DEFAULT '0x61',
  f_protocol VARCHAR(64) NOT NULL DEFAULT 'mock-perp',
  f_contract_address VARCHAR(64) NULL,
  f_tx_hash VARCHAR(128) NOT NULL,
  f_tx_status VARCHAR(16) NOT NULL DEFAULT 'submitted' COMMENT 'submitted/confirmed/failed/closed/cancelled',
  f_receipt_status VARCHAR(8) NULL COMMENT 'EVM receipt status, 0x1/0x0',
  f_block_number VARCHAR(32) NULL,
  f_symbol VARCHAR(32) NOT NULL,
  f_pair_label VARCHAR(96) NOT NULL DEFAULT '',
  f_market_type VARCHAR(16) NOT NULL DEFAULT 'perp',
  f_side VARCHAR(8) NOT NULL,
  f_order_type VARCHAR(16) NOT NULL DEFAULT 'market',
  f_margin_usdt DECIMAL(30, 10) NOT NULL,
  f_leverage DECIMAL(18, 6) NOT NULL,
  f_leverage_x100 INT NULL,
  f_notional_usdt DECIMAL(30, 10) NULL,
  f_slippage_percent DECIMAL(18, 8) NULL,
  f_entry_price DECIMAL(30, 10) NULL,
  f_exit_price DECIMAL(30, 10) NULL,
  f_pnl_usdt DECIMAL(30, 10) NULL,
  f_pnl_percent DECIMAL(18, 8) NULL,
  f_strategy_id VARCHAR(64) NULL,
  f_strategy_name VARCHAR(128) NULL,
  f_agent_id VARCHAR(64) NULL,
  f_agent_name VARCHAR(128) NULL,
  f_signal_id VARCHAR(64) NULL,
  f_source VARCHAR(32) NOT NULL DEFAULT 'web',
  f_raw_order_json JSON NULL,
  f_raw_receipt_json JSON NULL,
  f_create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  f_update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (f_id),
  UNIQUE KEY uniq_chain_order_id (f_order_id),
  UNIQUE KEY uniq_chain_order_tx_hash (f_tx_hash),
  KEY idx_chain_order_user_time (f_user_id, f_create_time),
  KEY idx_chain_order_user_status (f_user_id, f_tx_status),
  KEY idx_chain_order_user_strategy (f_user_id, f_strategy_id),
  KEY idx_chain_order_symbol_time (f_symbol, f_create_time),
  KEY idx_chain_order_wallet_time (f_wallet_address, f_create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
